<?php
function getusersforreport()
{
	require("includes/config.php");
	$users = mysql_query("SELECT `id`,`firstname`,`lastname`, `year`, `group_id` FROM `users` WHERE `admin` =0 ORDER BY `lastname` ASC;");
	return $users;
}

$report = $_REQUEST['reportid'];
if($report == "") header("Location: 404");
$reporttype = $_REQUEST['reporttype'];
$directout = $_REQUEST['directout'];
include_once("includes/config.php");
include_once("includes/displayfunc.php");
include_once("includes/sysfunc.php");
include_once("includes/sessionhandler.php");

$basefilename = "reportcache/rep".$report;
$cachefilename = $basefilename.".".$reporttype;
$user_details = $_SESSION['userdetails'];
$activitydetails = $_SESSION['activitydetails'];

if(file_exists($cachefilename.".config"))
{
	if($_REQUEST['refresh'] == "yes" || (time() - file_get_contents($cachefilename.".config")) > $timetokeepreports)
	{
		@unlink($basefilename.".html");
		@unlink($basefilename.".csv");
		@unlink($basefilename.".html.config");
		@unlink($basefilename.".csv.config");
	}
}
if(!file_exists($cachefilename))
{
	if($reporttype != "pdf")
	{
		ob_start();
		$con = mysql_connect($mysql_host, $mysql_user, $mysql_pass) or die("Could not connect to MySQL server!");
		mysql_select_db($mysql_db, $con) or die("Could not select $site_title_text database!");
		$moodle_users = FALSE;
		if($reporttype != "csv")
		{
		?>
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
			<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
			<title><?php print $reports[$report]; ?> - Report Generated by <?php print $site_title_text; ?></title>
			<style type="text/css" >
				<?php include_once("css/report.css"); ?>
			</style>
			</head>
			<body>
			<div class="report_header">
		<?php 
		}
		print $reports[$report]." - Report Generated by ".$site_title_text;
		if($reporttype != "csv") { 
			?></div><?php
		} else {
			print "\r\n\r\n"; 
		}
	}
	
	$users = getusersforreport();
	$usernum = mysql_num_rows($users);
	
	$filename = "includes/reports/".stripspaces_andlower($reports[$report]).".php";
	include_once($filename);
	
	if($reporttype != "pdf")
	{
		if(stripspaces_andlower($reports[$report]) != "activityregister")
		{
			$footerstring = "Generated on ".date("d F Y")." at ".date("H:i")." by ".$user_details->firstname." ".$user_details->lastname;
			if($reporttype == "csv")
			{
				print "\r\n".$footerstring;
			} else {
			?>
				<div id="footer"><?php print $footerstring; ?></div>
			<?php
			}
		}
		if($reporttype != "csv")
		{
		?>
			</body>
			</html>
		<?php
		}
		$content = ob_get_clean();
	}
	switch($reporttype)
	{
	case "html":
	case "csv":
		file_put_contents($cachefilename, $content);
	break;
	}
	file_put_contents($cachefilename.".config", time());
	mysql_close($con);
}

$content = file_get_contents($cachefilename);
$date = date("d-m-Y");
$outfilename = strtolower($site_title_text)."_report_".stripspaces_andlower($reports[$report])."_$date";
switch($reporttype)
{
case "html":
	if($directout == "Yes")
	{
		header('Content-Type: text/html');
		header('Content-Length: '.strlen($content));
		header('Content-Disposition: attachment; filename="'.$outfilename.'.html"');
	}
	print $content;
break;
case "csv":
	header('Content-Type: text/csv');
	header('Content-Length: '.strlen($content));
	header('Content-Disposition: attachment; filename="'.$outfilename.'.csv"');
	print $content;
break;
}
?>
